### ISSUE TITLE
Bug: All Icons not loading in Safari & Firefox on both Mac and iOS

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#370] opened 2021-03-03 12:41 UTC
Dear support,

I'm working with the latest Zion Builder Free & Pro version and noticed that icons are not loading on Safari and Firefox on both my MacBook and iPhone XR. All I can see is a square outline indicating the icons couldn't load.

**Describe the bug**
Icons don't load on Safari and Firefox on Macbook and iPhone.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add any element that has an icon. Example: a button, icon list etc.
2. View the page with Firefox and/or Safari on a mac or iPhone
3. Icons should be missing and it should show a rectangular outline.

**Expected behavior**
Being able to see the icons in Safari and Firefox.

**What actually happens**
Icons are not loaded and the website displays an rectangular outline instead.

**Screenshots/Videos**

Screenshot from Safari on Mac
<img width="1322" alt="Schermafbeelding 2021-03-03 om 13 37 35" src="https://user-images.githubusercontent.com/6600256/109806975-9f1c5380-7c25-11eb-813f-e2bdc6872e43.png">

Screenshot from Firefox on Mac
<img width="1178" alt="Schermafbeelding 2021-03-03 om 13 39 21" src="https://user-images.githubusercontent.com/6600256/109807213-e0146800-7c25-11eb-86ee-53ddf5f787ff.png">

**Environment (please complete the following information):**
- OS: MacOS Big Sur 11.0.1 (20B50) & iPhone XR 13.3.1
- Safari version 14.0.1 & Firefox version 84.0.1 (64-bits)
- Zionbuilder Free Version 2.0.0
- Zionbuilder Pro Version 2.0.0

**Comment by zauan** [comment] 2021-03-03 13:39
As discussed, this issue is caused by wp fastest cache which removes the quotes from icon URLs, without checking if those quotes are actually necessary ( the quotes are necessary when having white spaces in the URL, which is the case of font awesome ).

this was resolved in https://github.com/zionbuilder/zionbuilder/pull/371

**Closed by zauan** 2021-03-03 13:39 UTC
