### ISSUE TITLE
CSS Class on row (Column element) not working / Row Element suggestion

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#114] opened 2020-09-21 09:52 UTC
**Describe the bug**
Since Zion Builder doesn't have a row element I decided to create this with an extra Column Element.
So my structure is:

• Section (Section Element)
   - Row (Column Element with custom css class 'be-row')
      • Column 1 (Column Element)
      • Column 2 (Column Element)

This 'Row' with class 'be-row' only has top and bottom padding of 40px.
In the Zion Builder it works perfectly. However when I view the page and inspect this element, the CSS won't show up in the inspector as if it doesn't exist.

— — — Suggestion: Row Element — — —
Is it an idea to have a row element?
It can be the same as a column element but just with its own Zion classes ie:

    .zb-row
    .zb-el-zionRow

The main reason for this is the label and ease of use in Zion Builder, when we have more nested columns it would be much more user friendly to see which elements are used as actual columns and which elements are rows.

As of now we have to create a 'row' element ourselves and rename it in the tree view. An actual 'Row' element in this case would save a lot of time as we can easily just drag and drop 'Rows' to quickly build our layouts.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Go open any page in Zion Builder.
2. Add a section with one column.
3. Give this column a class for example 'be-row' with a top & bottom padding of 40px and left & right padding of 0.
3. Put two columns inside it and fill it with any content.

**Expected behavior**

You should have a Row (Column element) that you can now duplicate for easily stacking rows.

**What actually happens**
The above setup works in Zion Builder but not when viewing the actual page as my custom class is nowhere to be seen in the browser inspector.

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*

**Environment (please complete the following information):**
- MacOS 10.15.1
- Chrome 85.0.4183.102
- Zionbuilder Version 1.0.1

**Additional context**
I have already provided admin login credentials to Stefan for the website where this is occuring.
Please let me know if I need to provide anything else.

Best regards,
Christiaan

**Comment by raluseru** [comment] 2020-09-21 10:09
Hi! 

I cannot reproduce this issue on my local machine. Please try and add classes as explained in this article of documentation. Let me know if you still encounter the problem.

[(https://zionbuilder.io/documentation/global-css-classes/)]

Also, the section acts as a "row" - so there is no need to add extra columns inside the section. In order to maintain the page with a simple structure, I recommend you add directly a 2 columns  section, instead of a section with a column and inside a column adding 2 columns. 

Best regards!

Raluca

**Comment by zauan** [comment] 2020-09-21 10:13
Hi, 

I will look into this as I have access to the problem. Will get back with a solution

**Comment by zauan** [comment] 2020-09-21 11:20
This has been fixed in https://github.com/zionbuilder/zionbuilder/pull/117

A pre-release was created and the full fix will be available in v1.0.2 ( https://github.com/zionbuilder/zionbuilder/releases/tag/v1.0.2 )

**Closed by zauan** 2020-09-21 11:20 UTC
